#!/bin/bash

# --- k3s server installation ---
# install K3s in server mode and bind it to the Vagrant private network interface
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110 --flannel-iface=eth1" sh -

# wait to ensure the token file is generated by K3s
sleep 15

# change perm. of the config. file for the vagrant user
sudo chmod 644 /etc/rancher/k3s/k3s.yaml

# copy the node-token to the shared dir. to make it accessible to the worker node
sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token

# --- ssh config. ---
# generate a shared SSH key pair for the cluster if it doesn't exist in the shared folder
if [ ! -f /vagrant/cluster_key ]; then
    ssh-keygen -t rsa -b 4096 -N "" -f /vagrant/cluster_key
fi

# copy the shared key to the vagrant user's .ssh dir.
cp /vagrant/cluster_key /home/vagrant/.ssh/id_rsa
cp /vagrant/cluster_key.pub /home/vagrant/.ssh/id_rsa.pub

# authorize the public key to allow incoming passwordless connections
cat /vagrant/cluster_key.pub >> /home/vagrant/.ssh/authorized_keys

# set strict perm. required by SSH
chown -R vagrant:vagrant /home/vagrant/.ssh
chmod 600 /home/vagrant/.ssh/id_rsa
chmod 644 /home/vagrant/.ssh/id_rsa.pub
