#!/bin/bash

# -- k3s agent installation --
# wait to ensure the server has fully started and copied the token
sleep 10

# read the token from the shared dir.
export K3S_TOKEN=$(cat /vagrant/node-token)

# install K3s in agent mode, pointing to the server's static IP
curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 INSTALL_K3S_EXEC="--node-ip=192.168.56.111 --flannel-iface=eth1" sh -

# -- ssh config. --
# wait for the shared SSH key to be generated by the server
while [ ! -f /vagrant/cluster_key ]; do 
    sleep 2
done

# copy the shared key to the vagrant user's .ssh dir.
cp /vagrant/cluster_key /home/vagrant/.ssh/id_rsa
cp /vagrant/cluster_key.pub /home/vagrant/.ssh/id_rsa.pub

# authorize the public key to allow incoming passwordless connections
cat /vagrant/cluster_key.pub >> /home/vagrant/.ssh/authorized_keys

# set strict perm. required by SSH
chown -R vagrant:vagrant /home/vagrant/.ssh
chmod 600 /home/vagrant/.ssh/id_rsa
chmod 644 /home/vagrant/.ssh/id_rsa.pub
